# Generated by Django 4.2.1 on 2023-05-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.academicyear')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.item')),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=24)),
                ('degree', models.IntegerField(choices=[(-1, 'Master'), (0, 'Doctor'), (1, 'Professor'), (2, 'Other')], default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherItemYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.academicyear')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.item')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='items',
            field=models.ManyToManyField(related_name='teacher_items', through='teacher.TeacherItemYear', to='student.item'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_passed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('finish_at', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.level')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('references', models.FileField(upload_to='student')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.item')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.level')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.localization')),
                ('present_students', models.ManyToManyField(related_name='lesson_present_students', to='student.student')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.reunion')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='localization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.localization'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='teacher.StudentExam', to='student.student'),
        ),
    ]
