# Generated by Django 4.2.1 on 2023-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_academicyear_students_student_academic_years_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='student.item'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='student.student'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='items',
            field=models.ManyToManyField(related_name='teachers', through='teacher.TeacherItemYear', to='student.item'),
        ),
    ]
