# Generated by Django 4.2.1 on 2023-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
