# Generated by Django 4.2.1 on 2023-06-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_education_alter_student_diploma_and_more'),
        ('teacher', '0002_alter_rating_item_alter_rating_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='exams', through='teacher.StudentExam', to='student.student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='student.item'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='student.level'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='present_students',
            field=models.ManyToManyField(related_name='lessons', to='student.student'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='student.level'),
        ),
    ]
