# Generated by Django 4.2.1 on 2023-06-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_education_alter_student_diploma_and_more'),
        ('teacher', '0003_alter_exam_students_alter_lesson_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='student.item'),
        ),
    ]
