# Generated by Django 4.2.1 on 2023-06-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_exam_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='notice',
            field=models.TextField(default='notice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
