# Generated by Django 4.2.1 on 2023-06-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_education_alter_student_diploma_and_more'),
        ('teacher', '0005_rating_notice_alter_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='references',
            field=models.FileField(blank=True, upload_to='student'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='student.academicyear'),
        ),
    ]
