# Generated by Django 4.2.1 on 2023-06-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_education_alter_student_diploma_and_more'),
        ('teacher', '0006_alter_lesson_references_alter_reunion_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='teacheritemyear',
            unique_together={('teacher', 'item', 'academic_year')},
        ),
    ]
