# Generated by Django 4.2.1 on 2023-06-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='diploma',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
