# Generated by Django 4.2.1 on 2023-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_years',
            field=models.ManyToManyField(related_name='students', to='student.academicyear'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='items',
            field=models.ManyToManyField(related_name='academicyears', through='student.StudentItemYear', to='student.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='students',
            field=models.ManyToManyField(related_name='items', through='student.StudentItemYear', to='student.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='diploma',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='workplace',
            field=models.TextField(blank=True),
        ),
    ]
