# Generated by Django 4.2.1 on 2023-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_academicyear_students_student_academic_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.IntegerField(choices=[(-1, 'Higher'), (0, 'Secondary'), (1, 'Vocational'), (2, 'Primary'), (3, 'Other')], default=-1),
        ),
        migrations.AlterField(
            model_name='student',
            name='diploma',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
