# Generated by Django 4.2.1 on 2024-01-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.academicyear'),
            preserve_default=False,
        ),
    ]
