# Generated by Django 4.2.1 on 2024-01-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_level_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='student.academicyear'),
        ),
    ]
