# Generated by Django 4.2.1 on 2023-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_education_alter_student_diploma_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentitemyear',
            unique_together={('student', 'item', 'academic_year')},
        ),
    ]
